# Generated by Django 5.2.7 on 2025-10-28 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('contato', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hd', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('tamanho_total_gb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tamanho_livre_gb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('localizacao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('LIVRE', 'Livre (Aguardando Projeto)'), ('EM_USO', 'Em Uso (Projeto Ativo)'), ('ARQUIVADO', 'Arquivado (Dados Completos)'), ('MANUTENCAO', 'Manutenção/Defeito')], default='LIVRE', max_length=20)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdm_manager.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoPastaRaiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pasta', models.CharField(max_length=255)),
                ('caminho_raiz', models.CharField(max_length=500)),
                ('tamanho_ocupado_gb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_adicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('hd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdm_manager.hd')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdm_manager.trabalho')),
            ],
            options={
                'verbose_name': 'Conteúdo/Pasta Raiz',
                'verbose_name_plural': 'Conteúdos/Pastas Raiz',
            },
        ),
    ]
